class AddCountries < ActiveRecord::Migration
  def self.up
    Country.delete_all
    #    Country.create(:name => "",                   :code            => "")
    Country.create(:name => "Austria",                 :code            => "AT")
    Country.create(:name => "Belarus",                 :code            => "BY")
    Country.create(:name => "Belgium",                 :code            => "BE")
    Country.create(:name => "Bosnia and Herzegovina",  :code            => "BA")
    Country.create(:name => "Bulgaria",                :code            => "BG")
    Country.create(:name => "Croatia",                 :code            => "HR")
    Country.create(:name => "Czech Republic",          :code            => "CZ")
    Country.create(:name => "Denmark",                 :code            => "DK")
    Country.create(:name => "Estonia",                 :code            => "EE")
    Country.create(:name => "Finland",                 :code            => "FI")
    Country.create(:name => "France",                  :code            => "FR")
    Country.create(:name => "Georgia",                 :code            => "GE")
    Country.create(:name => "Germany",                 :code            => "DE")
    Country.create(:name => "Gibraltar",               :code            => "GI")
    Country.create(:name => "Greece",                  :code            => "GR")
    Country.create(:name => "Greenland",               :code            => "GL")
    Country.create(:name => "Hungary",                 :code            => "HU")
    Country.create(:name => "Iceland",                 :code            => "IS")
    Country.create(:name => "Ireland",                 :code            => "IE")
    Country.create(:name => "Italy",                   :code            => "IT")
    Country.create(:name => "Latvia",                  :code            => "LV")
    Country.create(:name => "Liechtenstein",           :code            => "LI")
    Country.create(:name => "Lithuania",               :code            => "LT")
    Country.create(:name => "Luxembourg",              :code            => "LU")
    Country.create(:name => "Malta",                   :code            => "MT")
    Country.create(:name => "Moldova, Republic of",    :code            => "MD")
    Country.create(:name => "Montenegro",              :code            => "ME")
    Country.create(:name => "Netherlands",             :code            => "NL")
    Country.create(:name => "Norway",                  :code            => "NO")
    Country.create(:name => "Poland",                  :code            => "PL")
    Country.create(:name => "Portugal",                :code            => "PT")
    Country.create(:name => "Romania",                 :code            => "RO")
    Country.create(:name => "Russian Federation",      :code            => "RU")
    Country.create(:name => "Serbia",                  :code            => "RS")
    Country.create(:name => "Slovakia",                :code            => "SK")
    Country.create(:name => "Slovenia",                :code            => "SI")
    Country.create(:name => "Spain",                   :code            => "ES")
    Country.create(:name => "Sweden",                  :code            => "SE")
    Country.create(:name => "Switzerland",             :code            => "CH")
    Country.create(:name => "Turkey",                  :code            => "TR")
    Country.create(:name => "Ukraine",                 :code            => "UA")
    Country.create(:name => "United Kingdom",          :code            => "GB")
  end

  def self.down
  end
end
